### ISSUE TITLE
No available camera can be found.

### ISSUE THREAD

**Issue by wwdok** [nikishovde/CameraX-EXTERNAL#1]
Hi @nikishovde , i came here from your [answer](https://stackoverflow.com/a/62690486/12169382) in stackoverflow, my device is [hikey970](https://www.96boards.org/product/hikey970/) with a usb camera, the output log of `adb shell dumpsys media.camera` is :
```
== Service global info: ==

Number of camera devices: 1
Number of normal camera devices: 1
    Device 0 maps to "/dev/video0"
Active Camera Clients:
[]
Allowed user IDs: 0

== Camera service events log (most recent at top): ==
  12-11 07:11:45 : DISCONNECT device /dev/video0 client for package org.tensorflow.lite.examples.detection (PID 0)
  12-11 07:11:45 : DIED client(s) with PID 2582, reason: (Binder died unexpectedly)
  12-11 07:11:35 : CONNECT device /dev/video0 client for package org.tensorflow.lite.examples.detection (PID 6183)
  12-11 07:11:35 : DISCONNECT device /dev/video0 client for package com.sample.textureview (PID 6094)
  12-11 07:11:35 : EVICT device /dev/video0 client held by package com.sample.textureview (PID 6094, score 200, state 2)
 - Evicted by device /dev/video0 client for package org.tensorflow.lite.examples.detection (PID 6183, score 0, state 2)
  12-11 07:11:08 : CONNECT device /dev/video0 client for package com.sample.textureview (PID 6094)
  12-11 07:11:07 : DISCONNECT device /dev/video0 client for package com.example.iguardonmzlt2 (PID 5635)
  12-11 07:10:30 : CONNECT device /dev/video0 client for package com.example.iguardonmzlt2 (PID 5635)
  12-11 07:07:35 : ADD device /dev/video0, reason: (Device added)
  12-11 07:05:00 : REMOVE device /dev/video0, reason: (Device status changed from 1 to 0)
  12-11 07:02:42 : USER_SWITCH previous allowed user IDs: <None>, current allowed user IDs: 0
  01-01 00:14:55 : ADD device /dev/video0, reason: (Device added)
  01-01 00:14:55 : ADD device /dev/video0, reason: (Device status changed from 0 to 1)

== Camera device /dev/video0 dynamic info: ==
  Device /dev/video0 is closed, no client instance
== Camera Provider HAL external/0 (v2.4, remote) static info: 1 devices: ==
== Camera HAL device device@3.4/external//dev/video0 (v3.4) static information: ==
  Resource cost: 100
  Conflicting devices: None
  API1 info:
    Has a flash unit: false
    Facing: Front
    Orientation: 0
  API2 camera characteristics:
    Dumping camera metadata array: 52 / 52 entries, 1256 / 1256 bytes of extra data.
      Version: 1, Flags: 00000000
      android.info.supportedHardwareLevel (150000): byte[1]
        [EXTERNAL ]
      android.colorCorrection.availableAberrationModes (00004): byte[1]
        [0 ]
      android.control.aeAvailableAntibandingModes (10012): byte[1]
        [3 ]
      android.control.maxRegions (1001c): int32[3]
        [0 0 0 ]
      android.control.availableVideoStabilizationModes (1001a): byte[1]
        [0 ]
      android.control.awbAvailableModes (1001b): byte[1]
        [1 ]
      android.control.aeAvailableModes (10013): byte[1]
        [1 ]
      android.control.availableEffects (10018): byte[1]
        [0 ]
      android.control.availableModes (10026): byte[2]
        [0 1 ]
      android.edge.availableEdgeModes (30002): byte[1]
        [0 ]
      android.flash.info.available (50000): byte[1]
        [FALSE ]
      android.hotPixel.availableHotPixelModes (60001): byte[1]
        [0 ]
      android.jpeg.availableThumbnailSizes (70007): int32[4]
        [0 0 240 180 ]
      android.jpeg.maxSize (70008): int32[1]
        [5242880 ]
      android.lens.info.focusDistanceCalibration (90007): byte[1]
        [UNCALIBRATED ]
      android.lens.info.availableOpticalStabilization (90003): byte[1]
        [0 ]
      android.lens.facing (80005): byte[1]
        [EXTERNAL ]
      android.noiseReduction.availableNoiseReductionModes (a0002): byte[1]
        [0 ]
      android.noiseReduction.mode (a0000): byte[1]
        [OFF ]
      android.request.availableCapabilities (c000c): byte[1]
        [BACKWARD_COMPATIBLE ]
      android.request.partialResultCount (c000b): int32[1]
        [1 ]
      android.request.pipelineMaxDepth (c000a): byte[1]
        [4 ]
      android.request.maxNumOutputStreams (c0006): int32[3]
        [0 2 1 ]
      android.request.maxNumInputStreams (c0008): int32[1]
        [0 ]
      android.scaler.availableMaxDigitalZoom (d0004): float[1]
        [1.00000000 ]
      android.scaler.croppingType (d000d): byte[1]
        [CENTER_ONLY ]
      android.sensor.availableTestPatternModes (e0019): int32[1]
        [0 ]
      android.sensor.info.timestampSource (f0008): byte[1]
        [UNKNOWN ]
      android.sensor.orientation (e000e): int32[1]
        [0 ]
      android.shading.availableModes (100002): byte[1]
        [0 ]
      android.statistics.info.availableFaceDetectModes (120000): byte[1]
        [0 ]
      android.statistics.info.maxFaceCount (120002): int32[1]
        [0 ]
      android.statistics.info.availableHotPixelMapModes (120006): byte[1]
        [0 ]
      android.statistics.info.availableLensShadingMapModes (120007): byte[1]
        [0 ]
      android.sync.maxLatency (170001): int32[1]
        [UNKNOWN ]
      android.request.availableRequestKeys (c000d): int32[27]
        [3 65536 65537 65538 ]
        [65539 65542 65541 65543 ]
        [65545 65546 65547 65549 ]
        [65550 65551 65552 65553 ]
        [262146 458755 458756 458757 ]
        [458758 524292 655360 851968 ]
        [917528 1114112 1114115 ]
      android.request.availableResultKeys (c000e): int32[34]
        [3 65536 65537 65538 ]
        [65539 65542 65567 65541 ]
        [65543 65568 65545 65546 ]
        [65547 65570 65549 65550 ]
        [65551 65552 65553 262146 ]
        [262149 458755 458756 458757 ]
        [458758 524292 655360 786441 ]
        [851968 917520 1114112 1114115 ]
        [1114128 1114126 ]
      android.request.availableCharacteristicsKeys (c000f): int32[42]
        [4 65554 65555 65556 ]
        [65557 65558 65572 65559 ]
        [65560 65574 65561 65562 ]
        [65563 65573 65564 327680 ]
        [1376256 458759 524293 589827 ]
        [589831 655362 786444 786440 ]
        [786438 786443 786442 851972 ]
        [851978 851981 983040 983044 ]
        [983046 983050 983048 917518 ]
        [1048578 1179648 1179654 1179655 ]
        [1179650 1507329 ]
      android.control.aeCompensationRange (10015): int32[2]
        [0 0 ]
      android.control.aeCompensationStep (10016): rational[1]
        [(0 / 1) ]
      android.control.afAvailableModes (10017): byte[2]
        [1 0 ]
      android.control.availableSceneModes (10019): byte[1]
        [0 ]
      android.control.aeLockAvailable (10024): byte[1]
        [FALSE ]
      android.control.awbLockAvailable (10025): byte[1]
        [FALSE ]
      android.control.aeAvailableTargetFpsRanges (10014): int32[2]
        [15 30 ]
      android.scaler.availableStreamConfigurations (d000a): int32[36]
        [33 320 240 OUTPUT ]
        [35 320 240 OUTPUT ]
        [34 320 240 OUTPUT ]
        [33 352 288 OUTPUT ]
        [35 352 288 OUTPUT ]
        [34 352 288 OUTPUT ]
        [33 640 480 OUTPUT ]
        [35 640 480 OUTPUT ]
        [34 640 480 OUTPUT ]
      android.scaler.availableMinFrameDurations (d000b): int64[36]
        [33 320 ]
        [240 33333333 ]
        [35 320 ]
        [240 33333333 ]
        [34 320 ]
        [240 33333333 ]
        [33 352 ]
        [288 33333333 ]
        [35 352 ]
        [288 33333333 ]
        [34 352 ]
        [288 33333333 ]
        [33 640 ]
        [480 33333333 ]
        [35 640 ]
        [480 33333333 ]
        [34 640 ]
        [480 33333333 ]
      android.scaler.availableStallDurations (d000c): int64[36]
        [33 320 ]
        [240 1000000000 ]
        [35 320 ]
        [240 0 ]
        [34 320 ]
        [240 0 ]
        [33 352 ]
        [288 1000000000 ]
        [35 352 ]
        [288 0 ]
        [34 352 ]
        [288 0 ]
        [33 640 ]
        [480 1000000000 ]
        [35 640 ]
        [480 0 ]
        [34 640 ]
        [480 0 ]
      android.sensor.info.maxFrameDuration (f0004): int64[1]
        [66666666 ]
      android.sensor.info.preCorrectionActiveArraySize (f000a): int32[4]
        [0 0 640 480 ]
      android.sensor.info.activeArraySize (f0000): int32[4]
        [0 0 640 480 ]
      android.sensor.info.pixelArraySize (f0006): int32[2]
        [640 480 ]
== Camera HAL device device@3.4/external//dev/video0 (v3.4) dumpState: ==
No active camera device session instance

== Vendor tags: ==

  Dumping vendor tag descriptors for vendor with id 2592128789
  Dumping configured vendor tag descriptors: None set

== Camera error traces (0): ==
  No camera traces collected.
```
When i am launch this app on hikey970, tap `TAKE PHOTO`, the output of Android Studio is : 
```
03/24 09:20:45: Launching 'app' on unknown AOSP on hikey970.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.example.camera2/com.example.camera2.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 8614 on device 'unknown-aosp_on_hikey970-192.168.53.102:6666'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/example.camera: Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
W/example.camera: Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
W/example.camera: Accessing hidden method Landroid/view/View;->getAccessibilityDelegate()Landroid/view/View$AccessibilityDelegate; (light greylist, linking)
W/example.camera: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/example.camera: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
W/example.camera: Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
I/CameraManagerGlobal: Connecting to camera service
D/CameraRepository: Added camera: /dev/video0
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL
D/UseCaseAttachState: Active and attached use case: [] for camera: /dev/video0
D/OpenGLRenderer: Skia GL Pipeline
E/CameraXBasic: Use case binding failed
    java.lang.IllegalArgumentException: No available camera can be found.
        at androidx.camera.core.CameraSelector.select(CameraSelector.java:81)
        at androidx.camera.core.CameraX.getCameraWithCameraSelector(CameraX.java:524)
        at androidx.camera.core.CameraX.bindToLifecycle(CameraX.java:331)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:255)
        at com.example.camera2.MainActivity$startCamera$1.run(MainActivity.kt:96)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
    android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport: Loading /vendor/lib64/hw/gralloc.hikey970.so from current namespace instead of sphal namespace.
D/vndksupport: Loading /vendor/lib64/hw/gralloc.hikey970.so from current namespace instead of sphal namespace.
D/vndksupport: Loading /vendor/lib64/hw/gralloc.hikey970.so from current namespace instead of sphal namespace.
D/vndksupport: Loading /vendor/lib64/hw/gralloc.hikey970.so from current namespace instead of sphal namespace.
E/CameraXBasic: Photo capture failed: Not bound to a valid Camera [ImageCapture:androidx.camera.core.ImageCapture-edfc0bea-c2ac-45f4-832a-89a4fe8c6354]
    androidx.camera.core.ImageCaptureException: Not bound to a valid Camera [ImageCapture:androidx.camera.core.ImageCapture-edfc0bea-c2ac-45f4-832a-89a4fe8c6354]
        at androidx.camera.core.ImageCapture.lambda$sendImageCaptureRequest$6$ImageCapture(ImageCapture.java:729)
        at androidx.camera.core.-$$Lambda$ImageCapture$2B91NcXQyr59NDscigcxsZb94mc.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ghost** [comment]
HI! As I can see your camera doesn't support resolution hardcoded in the RGBSurfaceManager:
```
...
        return mutableMapOf(newUseCaseConfigs[0] to Size(1920, 1080),
            newUseCaseConfigs[1] to Size(1920, 1080))
...
    override fun getPreviewSize(): Size {
        return Size(1920, 1080)
    }
```
Play around your camera supported resolutions:
```
...
      android.scaler.availableStreamConfigurations (d000a): int32[36]
        [33 320 240 OUTPUT ]
        [35 320 240 OUTPUT ]
        [34 320 240 OUTPUT ]
        [33 352 288 OUTPUT ]
        [35 352 288 OUTPUT ]
        [34 352 288 OUTPUT ]
        [33 640 480 OUTPUT ]
        [35 640 480 OUTPUT ]
        [34 640 480 OUTPUT ]
...
```

**Comment by wwdok** [comment]
I change resolution to 640 480, but it still has the same error : 
![image](https://user-images.githubusercontent.com/43233772/113801324-2dd34180-978b-11eb-9422-435d87783a54.png)
